# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f4a3fb02d9073d21c81eebc1872e5986"
name = "medic-star-staging"
handle = "medic-star-staging"
application_url = "https://shopify-app.stg.medicstar-service.de"
embedded = true

[build]
dev_store_url = "medicstar-app-dev.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders, write_inventory, read_locations, read_customers, write_assigned_fulfillment_orders, write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = ["https://shopify-app.stg.medicstar-service.de/auth/callback", "https://shopify-app.stg.medicstar-service.de/auth/shopify/callback", "https://shopify-app.stg.medicstar-service.de/api/auth/callback"]

[pos]
embedded = false

