name: "medicstar"

volumes:
  db-data:

services:
  remix:
    build:
      context: ./docker/node
      args:
        - UID=${UID}
        - GID=${GID}
        - USER_NAME=${USER_NAME}
    user: ${UID}:${GID}
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./medicstar-app:/app
      - ~/.config:/home/node/.config
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
  db:
    image: postgres
    restart: always
    shm_size: 1024mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 35432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 3080:80