# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f41436f31d7d26a7e195c8c61f7df78f"
name = "medicstar-app"
handle = "medicstar-app"
application_url = "https://356184962573.ngrok-free.app"
embedded = true

[build]
dev_store_url = "medicstar-app-dev.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order/create"


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_orders, write_orders, write_inventory, read_locations, read_customers, write_assigned_fulfillment_orders, write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = ["https://356184962573.ngrok-free.app/auth/callback", "https://356184962573.ngrok-free.app/auth/shopify/callback", "https://356184962573.ngrok-free.app/api/auth/callback"]

[pos]
embedded = false

