networks:

services:
  postgres:
    image: postgres:14.18
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:   ${POSTGRES_DB}
  app:
    build:
      context: ..
      dockerfile: ./docker/node/Dockerfile
    restart: always
    command: sh -c "npm run setup && npm run pm2-start && npm run pm2-logs"
    depends_on:
      - postgres
volumes:
  db-data:
